### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by fedekk2014** [Silari/Silari-Factorio-Mods#2]
Update for 2.0?

**Comment by Silari** [comment]
It'll probably be the next one I work on. Only a couple of my mods aren't updated at this point.

**Comment by Silari** [comment]
2.0.0 has been released. It provides support for basic mode only. Advanced support should come soon.

Support for other mods is theoretical as they haven't updated. Krastorio 2 support removed, it won't be getting a 2.0 release.
